In [1]:
import pandas as pd
import numpy as np

input_file = './test2A_prompts.txt'
output_file = None

# Leer el archivo de entrada
df = pd.read_csv(input_file, sep='\s+')

# Verificar que las columnas esperadas estén presentes
expected_columns = {'frame', 'x', 'y', 'isin'}
if not expected_columns.issubset(df.columns):
    raise ValueError(f"El archivo de entrada debe contener las columnas: {expected_columns}")

In [33]:
ann_frame_idx_list = list(df.groupby('frame').groups.keys())
ann_frame_idx_list

[571,
 901,
 903,
 933,
 1024,
 1025,
 1041,
 1156,
 1170,
 1272,
 2681,
 2935,
 3185,
 4571,
 5652]

In [34]:
ann_obj_id = 32
points_list = [np.array(df[df['frame'] == frame_idx][['x', 'y']].values, dtype = np.float32) for frame_idx in ann_frame_idx_list]
points_list

[array([[822., 662.],
        [822., 672.],
        [796., 661.],
        [838., 665.]], dtype=float32),
 array([[1046.,  375.],
        [1051.,  365.],
        [1047.,  386.]], dtype=float32),
 array([[1039.,  345.],
        [1052.,  352.]], dtype=float32),
 array([[906., 408.],
        [901., 425.]], dtype=float32),
 array([[1075.,  381.],
        [1069.,  370.],
        [1086.,  380.]], dtype=float32),
 array([[1077.,  372.],
        [1066.,  379.],
        [1089.,  376.],
        [1068.,  371.]], dtype=float32),
 array([[1113.,  358.],
        [1106.,  364.]], dtype=float32),
 array([[1072.,  375.],
        [1071.,  364.],
        [1087.,  379.]], dtype=float32),
 array([[1100.,  368.],
        [1099.,  379.],
        [1107.,  354.]], dtype=float32),
 array([[1081.,  477.],
        [1069.,  480.],
        [1092.,  484.]], dtype=float32),
 array([[962., 493.],
        [963., 481.],
        [948., 490.],
        [977., 494.]], dtype=float32),
 array([[1029.,  446.],
        [1020.,  

In [35]:
labels_list = [np.array([isin for isin in df[df['frame'] == frame_idx]['isin']]) for frame_idx in ann_frame_idx_list]
labels_list

[array([1, 1, 0, 0]),
 array([1, 0, 0]),
 array([1, 0]),
 array([1, 0]),
 array([1, 0, 0]),
 array([1, 0, 0, 0]),
 array([1, 0]),
 array([1, 0, 0]),
 array([1, 0, 0]),
 array([1, 0, 0]),
 array([1, 1, 0, 0]),
 array([1, 0, 0]),
 array([1, 0, 0]),
 array([1, 0, 0]),
 array([1, 1, 1, 0, 0])]

In [36]:
# Escribir el codigo python correspondiente a la inicialización de las variables

print(f"ann_frame_idx_list = {ann_frame_idx_list}")
print(f"ann_obj_id = {ann_obj_id}")
print("points_list = [")
first = True
for points in points_list:
    if first:
        first = False
    else:
        print(",")
    print(f"    np.array({points.tolist()}, dtype=np.float32)", end="")
        
print("]")
print("labels_list = [")
first = True
for labels in labels_list:
    if first:
        first = False
    else:
        print(",")
    print(f"    np.array({labels.tolist()}, dtype=np.int32)", end="")
print("]")

ann_frame_idx_list = [571, 901, 903, 933, 1024, 1025, 1041, 1156, 1170, 1272, 2681, 2935, 3185, 4571, 5652]
ann_obj_id = 32
points_list = [
    np.array([[822.0, 662.0], [822.0, 672.0], [796.0, 661.0], [838.0, 665.0]], dtype=np.float32),
    np.array([[1046.0, 375.0], [1051.0, 365.0], [1047.0, 386.0]], dtype=np.float32),
    np.array([[1039.0, 345.0], [1052.0, 352.0]], dtype=np.float32),
    np.array([[906.0, 408.0], [901.0, 425.0]], dtype=np.float32),
    np.array([[1075.0, 381.0], [1069.0, 370.0], [1086.0, 380.0]], dtype=np.float32),
    np.array([[1077.0, 372.0], [1066.0, 379.0], [1089.0, 376.0], [1068.0, 371.0]], dtype=np.float32),
    np.array([[1113.0, 358.0], [1106.0, 364.0]], dtype=np.float32),
    np.array([[1072.0, 375.0], [1071.0, 364.0], [1087.0, 379.0]], dtype=np.float32),
    np.array([[1100.0, 368.0], [1099.0, 379.0], [1107.0, 354.0]], dtype=np.float32),
    np.array([[1081.0, 477.0], [1069.0, 480.0], [1092.0, 484.0]], dtype=np.float32),
    np.array([[962.0, 493.0], [96